# Generated by Django 2.2.4 on 2019-08-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('authors', models.CharField(default='', max_length=300)),
                ('url', models.URLField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('words', models.TextField()),
                ('publish_date', models.DateTimeField()),
                ('publisher', models.CharField(max_length=100)),
            ],
        ),
    ]
