# Generated by Django 2.2.4 on 2019-09-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub', models.CharField(max_length=100)),
                ('authors', models.CharField(default='', max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(default='', max_length=300)),
                ('published_at', models.DateTimeField()),
                ('downloaded_at', models.DateTimeField()),
                ('text', models.TextField()),
                ('description', models.TextField()),
                ('top_image', models.URLField(max_length=300)),
                ('url', models.URLField(max_length=300)),
                ('words', models.TextField()),
                ('language', models.CharField(max_length=50)),
            ],
        ),
    ]
