# Generated by Django 2.2.4 on 2019-08-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(default='', max_length=300)),
                ('url', models.URLField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('publisher', models.CharField(max_length=100)),
                ('words', models.TextField()),
            ],
        ),
    ]
