# Generated by Django 2.2.4 on 2019-09-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='authors',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='top_image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
