# Generated by Django 2.2.4 on 2019-08-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdata',
            name='category',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='newsdata',
            name='download_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
