# Generated by Django 2.2.4 on 2019-09-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190903_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='category',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
