# Generated by Django 2.2.4 on 2020-02-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nick',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
