# Generated by Django 2.2.4 on 2020-01-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('florence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='imports',
        ),
    ]
