# Generated by Django 2.2.4 on 2020-02-10 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('florence', '0002_user_nick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lib',
            name='author',
        ),
        migrations.AddField(
            model_name='extlib',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='intlib',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
