# Generated by Django 2.2.7 on 2019-12-22 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('florence', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
