# Generated by Django 2.2.7 on 2020-01-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florence', '0002_remove_module_imports'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='exports',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='imports',
            field=models.ManyToManyField(blank=True, related_name='_module_imports_+', to='florence.Module'),
        ),
        migrations.AddField(
            model_name='module',
            name='includes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
