# Generated by Django 2.2.7 on 2020-01-27 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('florence', '0003_auto_20200127_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='module',
            name='imports',
        ),
        migrations.RemoveField(
            model_name='module',
            name='includes',
        ),
        migrations.CreateModel(
            name='ImportUrl',
            fields=[
                ('import_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='florence.Import')),
                ('url', models.URLField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
            bases=('florence.import',),
        ),
        migrations.AddField(
            model_name='import',
            name='on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='florence.Module'),
        ),
        migrations.CreateModel(
            name='ImportModule',
            fields=[
                ('import_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='florence.Import')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='florence.Module')),
            ],
            options={
                'abstract': False,
            },
            bases=('florence.import',),
        ),
    ]
