# Generated by Django 2.2.4 on 2019-12-23 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('florence', '0003_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
