# Generated by Django 2.2.7 on 2020-01-27 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('florence', '0004_auto_20200127_1644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImportModule',
            new_name='ModuleImport',
        ),
        migrations.RenameModel(
            old_name='ImportUrl',
            new_name='UrlImport',
        ),
    ]
