# Generated by Django 2.2.4 on 2019-12-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florence', '0004_remove_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='imports',
            field=models.ManyToManyField(blank=True, related_name='_module_imports_+', to='florence.Module'),
        ),
    ]
