# Generated by Django 2.2.4 on 2019-12-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florence', '0005_module_imports'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='module',
            name='imports',
        ),
        migrations.AddField(
            model_name='module',
            name='imports',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
